### ISSUE TITLE
Can we extract out the QR Code that was generated with the logo.

### ISSUE THREAD

**Issue by VIkash2601** [SimonScholz/qr-code-with-logo#35]
First of all, thanks for this useful resource which reduced my efforts to integrate a **QR Code Scanner** in my existing app. I wonder if we can extract the logo from the existing QR Code with the logo image in it. The logo can be placed anywhere in the QR Code (mostly in the center).

**Comment by SimonScholz** [comment]
HI @VIkash2601,

what exactly do you mean by "extracting the logo"?
Is you intention to remove a logo from an existing QR Code?
Or do you want to be able to put the logo somewhere else on the QR code?

Would be nice if you could elaborate more on your needs.

Thanks!

**Comment by VIkash2601** [comment]
Hi @SimonScholz,

What I want to know is that if I already have a QR Code with my app's logo in the center of it, how can I extract the Logo as an image instead of the QR Code.

**Comment by SimonScholz** [comment]
Hi @VIkash2601,

well this is not the scope of this library. This library is capable to add a logo to a generated QR Code and it is not about extraction of a logo.
Why do you exactly have the purpose to extract a logo from an existing QR code?
Basically you would need to have some algorithm to recognize the boundaries the logo and then cut it out.
Do you have an example to illustrate your actual intention?

**Comment by SimonScholz** [comment]
@VIkash2601 since I did not hear from you since almost one month, I'll close this issue for now.
