### ISSUE TITLE
Can the borders expand to outside?

### ISSUE THREAD

**Issue by softwaremagico** [SimonScholz/qr-code-with-logo#60]
First, thanks for your effort on this library. As it is a good tool for QR codes, and there are not so many for Java. 

I have notice that playing around with the border radius, and the border size, in some cases generates QR that are not easy to read in some mobile phones. The issue is that when you expand the border, it overlaps with the QR code that is inside. 

It is easily reproducible with the demo application  from the project. For example, a qr code with size 500, border size 0.05 and border radius 0.02, causes that the border starts to be attached to the qr code:

![qr](https://github.com/SimonScholz/qr-code-with-logo/assets/6171537/3047b092-fe19-4a76-8cda-f6f0d66afc38)

But same configuration with different size (600px):

![qr](https://github.com/SimonScholz/qr-code-with-logo/assets/6171537/e12c9b62-6633-4c82-991e-4ee41369eeb3)

Or 400px:

![qr](https://github.com/SimonScholz/qr-code-with-logo/assets/6171537/2d784d91-ffd0-4cd6-af10-aecdca6e6d2b)

Works fine. 

As you can see, in general works fine, but in other cases not. Not a big issue, as I am choosing the configuration that fits better with my input, but I want you let it know. I also have tried with different content, and always seems that 500px is the combination that causes this issue.

Regards.

**Comment by SimonScholz** [comment]
Hi @softwaremagico,

I am glad you´ d appreciate the effort put into this library :)

Thanks for sharing the 3 sample qr codes with me. 
I´ll try to improve this behavior, which might cause maleficent qr codes.

This is the content of the QR CODE, right?

http://localhost/kendo-tournament-backend/tournaments/fights?tournamentId=-100&user=guest

Can you also share the type of Phone you´ re using to scan the qr codes?

My Pixel 6a is fine with all 3 of the qr codes you´ve shared and is capable to read all of them.

**Comment by softwaremagico** [comment]
I have a Moto G73, but I do not think that is related to the mobile but to the surface that overlaps with the qr code. Let me play around with the settings to try to exaggerate the error, and I will upload a new image with more surface overlapped. Because there are some combinations that can make the qr more difficult to read.

**Comment by softwaremagico** [comment]
I cannot reproduce any more. In fact, currently the border is below the QR code and cannot hide part of the QR code. I do not know which combination of settings I have used on my previous tests, but the closes I can do now, is the posted image before. That as you are commenting, the quality is good enough to be recognized with any modern mobile.
